package io.github.ieperen3039.ngn.Rendering.MeshLoading;

import io.github.ieperen3039.ngn.Rendering.MatrixStack.SGL;
import io.github.ieperen3039.ngn.AssetHandling.Asset;
import io.github.ieperen3039.ngn.AssetHandling.GeneratorAsset;
import io.github.ieperen3039.ngn.Tools.Vectors;

import java.nio.file.Path;

/**
 * @author Geert van Ieperen created on 17-11-2017.
 */
public interface Mesh {
    /**
     * draws the object on the gl buffer. This method may only be called by a class that implements SGL. To draw a mesh,
     * use {@link SGL#render(Mesh, Entity)}
     * @param lock a non-null object that can only be generated by a SGL object.
     */
    void render(SGL.Painter lock);

    /**
     * removes this mesh from the GPU. This method must be called exactly once before it is disposed
     */
    void dispose();

    /** creates a resource that cleans the meshfile it used whenever it reloads */
    static Asset<Mesh> createExternalAsset(Path path) {
        Asset<MeshFile> meshFile = MeshFile.createAsset(Vectors.Scaling.UNIFORM, path);

        return new GeneratorAsset<>(() -> {
            Mesh target = meshFile.get().getMesh();
            meshFile.drop();
            return target;
        }, Mesh::dispose);
    }

    static Asset<Mesh> emptyMesh() {
        return new GeneratorAsset<>(() -> EMPTY_MESH, null);
    }

    Mesh EMPTY_MESH = new Mesh() {
        @Override
        public void render(SGL.Painter lock) {
        }

        @Override
        public void dispose() {
        }

        @Override
        public String toString() {
            return "EMPTY_MESH";
        }
    };
}
